# Generated by Django 4.1.6 on 2023-02-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
